[ir.config_parameter]

;;; Specific Module: grap/grap-odoo-custom/server_environment_files

web_layout_path = /server_environment_files/static/dev/web_layout.css
point_of_sale_index_path = /server_environment_files/static/dev/point_of_sale_index.css


;;; Specific Module: OCA/web_environment_ribbon

ribbon.name=DEV<br/>{db_name}
ribbon.background.color=rgba(0,255,255,0.6)
ribbon.color=#333
