# Do NOT update manually; changes here will be overwritten by Copier
_commit: 78d9e21
_src_path: https://github.com/grap/oca-addons-repo-template-new.git
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_version: 12.0
org_name: Groupement Régional Alimentaire de Proximité (GRAP)
org_slug: grap
rebel_module_groups: []
repo_description: 'This repository contains Odoo modules developped by the company
    GRAP for custom needs. They are shared in the hope that it will be useful.


    You could be interesting too by the following repositories:'
repo_name: ' Custom Odoo modules for GRAP '
repo_slug: grap-odoo-custom
repo_website: https://github.com/grap/grap-odoo-custom
travis_apt_packages: []
travis_apt_sources: []

