language: python
sudo: false
cache: pip

python:
  - "2.7"

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow

env:
  global:
  - VERSION="8.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"

  # Weird conflict with grap_qweb_report and account_export_ebp
  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="OCA/OCB" UNIT_TEST="1"
  - TESTS="1" ODOO_REPO="OCA/OCB" EXCLUDE="account_export_ebp,grap_l10n_fr,grap_qweb_report"

virtualenv:
  system_site_packages: true

install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - sed -i -e 's/Odoo Community Association (OCA)/GRAP/g' ${HOME}/maintainer-quality-tools/travis/cfg/travis_run_pylint_pr.cfg
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
