from . import account_invoice
from . import account_invoice_line
from . import pos_order
from . import pos_order_line
from . import product_product
from . import product_supplierinfo
from . import product_template
from . import purchase_order_line
from . import sale_order
from . import sale_order_line
