from . import tools_generic
from . import tools_partner
from . import tools_product

bob = {
    "active": True,
    "sale_ok": True,
    "purchase_ok": True,
    "type": "consu",
    "categ_id": 1,
    "property_cost_method": False,
    "standard_price": 0,
    "company_id": 1,
    "uom_id": 1,
    "uom_po_id": 1,
    "available_in_pos": False,
    "invoice_policy": "order",
    "service_type": "manual",
    "expense_policy": "no",
    "sale_line_warn": "no-message",
    "print_category_id": False,
    "purchase_method": "receive",
    "purchase_line_warn": "no-message",
    "route_ids": [[6, False, [29]]],
    "sale_delay": 0,
    "tracking": "none",
    "property_stock_production": 7,
    "property_stock_inventory": 5,
    "property_account_income_id": False,
    "property_account_expense_id": False,
    "property_account_creditor_price_difference": False,
    "property_valuation": False,
    "property_stock_account_input": False,
    "property_stock_account_output": False,
    "image_medium": False,
    "__last_update": False,
    "name": "test",
    "is_consignment_commission": False,
    "default_code": False,
    "barcode": False,
    "label_ids": [[6, False, []]],
    "lst_price": 0,
    "fiscal_classification_id": False,
    "description": False,
    "pos_categ_id": False,
    "to_weight": False,
    "optional_product_ids": [[6, False, []]],
    "description_sale": False,
    "to_print": False,
    "seller_ids": [
        [
            0,
            "virtual_500",
            {
                "delay": 1,
                "product_tmpl_id": False,
                "min_qty": 0,
                "price": 10,
                "currency_id": 2,
                "company_id": 1,
                "product_variant_count": 0,
                "product_id": False,
                "name": 14,
                "product_name": False,
                "product_code": False,
                "discount": 15,
                "discount2": 16,
                "discount3": 17,
                "date_start": False,
                "date_end": False,
                "sequence": 0,
            },
        ]
    ],
    "service_to_purchase": False,
    "consignor_partner_id": False,
    "maker_description": False,
    "state_id": False,
    "department_id": False,
    "origin_type": False,
    "country_id": False,
    "country_group_id": False,
    "origin_description": False,
    "description_purchase": False,
    "net_weight": 0,
    "weight": 0,
    "volume": 0,
    "description_pickingout": False,
    "description_pickingin": False,
    "description_picking": False,
    "is_alimentary": False,
    "alcohol_by_volume": 0,
    "is_alcohol": False,
    "is_vegan": False,
    "is_uncertifiable": False,
    "use_by_date_day": 0,
    "best_before_date_day": 0,
    "storage_method": False,
    "ingredients": "<p><br></p>",
    "allergens": "<p><br></p>",
    "message_attachment_count": 0,
}
